folio-org/mod-gobi

.gitmodules
pom.xml
src/main/java/org/folio/gobi/GobiPurchaseOrderParser.java
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/Mapping.java
src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/gobi/HelperUtilsTest.java
src/test/java/org/folio/gobi/MappingTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/java/org/folio/rest/impl/PostGobiOrdersHelperTest.java
src/test/resources/GOBIIntegrationServiceResourceImpl/po_listed_print_monograph.xml
src/test/resources/Mapping/testdata.xml

See [MODGOBI-15](https://issues.folio.org/browse/MODGOBI-15) for details.
A Mapping consists of:
- `String from`:  an xpath expression
- `Object defValue`:  a default value
- `Function translation`:  an optional translation function
- `boolean translateDefault`:  whether or not the defValue should be run through the translator
Mappings are then associated with a Field enum value, e.g.
`mappings.put(Field.LIST_PRICE, new Mapping("//ListPrice/Amount", 0d, Mapper::toDouble));`
Finally, a Mapper class takes these mappings and applies them.  The end result is a CompositePurchaseOrder pojo. 
Eventually, the mappings can be stored in mod-configuration (as json) and updated/defined via UI.
Nested mappings are supported, so the default value of one mapping can be another mapping.  This allows you …

MODGOBI-15 - Implement Mapper

---

NEWS.md
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

see [MODGOBI-26](https://issues.folio.org/browse/MODGOBI-26)

return the po_line_number not po_number

---

NEWS.md
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java

see [MODGOBI-27](https://issues.folio.org/browse/MODGOBI-27)

CQL queries should be using '=='

---

NEWS.md
descriptors/ModuleDescriptor-template.json

See [MODGOBI-28](https://issues.folio.org/browse/MODGOBI-28)

Module descriptor needs to be updated with required interfaces

---

ramls/gobi.raml
src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/GOBIIntegrationServiceResourceImpl/test_ok.xml

Update GET  and POST endpoint to return an XML message and status code to 200
https://issues.folio.org/projects/MODGOBI/issues/MODGOBI-18

Modgobi 18 Update GET and POST endpoint

---

src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/data-mapping.json
src/test/java/org/folio/gobi/HelperUtilsTest.java
src/test/java/org/folio/rest/impl/PostGobiOrdersHelperTest.java

Addresses the following:
* [MODGOBI-38](https://issues.folio.org/browse/MODGOBI-38)
* Additional SonarQube issues:
* Code complexity of several functions
* Test coverage was below 80%
* Repeated String literal
* Unused variable

MODGOBI-38 and address sonarqube issues

---

ramls/schemas/GobiPurchaseOrder.xsd

updated the schema with the changes provided by the GOBI team.

New Schema changes

---

NEWS.md
pom.xml

Release 1.0.1

---

NEWS.md
PULL_REQUEST_TEMPLATE.md
README.md
src/main/java/org/folio/gobi/Mapper.java

https://issues.folio.org/browse/MODGOBI-43
**PURPOSE
Renewal information has been moved to composite PO level. The corresponding Mapping has to be changes for mapping a GOBI order
** Addition Information
There are fields that are changed in the schemas, Few of them are handled here(Created Date), but others are out of scope of this story(all **MetaData** fields) and will be handled as part of https://issues.folio.org/browse/MODGOBI-42

MODGOBI 43-MetaData Changes

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODGOBI-45
Releasing version 1.1.0 and preparing for next release 1.2.0
Followed the outlined steps in https://dev.folio.org/guidelines/release-procedures/

MODGOBI-45- Release 1.1.0

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

https://issues.folio.org/browse/MODGOBI-44
To use the modified endpoints on mod-orders. 
Point to use the latest /orders/composite-orders endpoint
This PR will be merged after https://issues.folio.org/browse/MODORDERS-124 has been merged. 
The unit tests are modified. But the API tests will be validated after merge.

pointing to new orders endpoint

---

README.md

Update the copyright year to 2019 as requested by @dcrossleyau

Changing copyright year to 2019

---

README.md

The copyright should be for a range (2018 - 2019), not just the most recent year

Copyright should be a range (2018 - 2019)

---

src/main/java/org/folio/gobi/GobiPurchaseOrderParser.java
src/main/java/org/folio/gobi/Mapper.java

Fix Sonar cloud security issues:
https://issues.folio.org/browse/MODGOBI-49
- Disable DTD and external DTD feature to protect against XML entity attacks
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

Sonar cloud security fix

---

src/main/java/org/folio/gobi/Mapper.java

To comply with this change https://github.com/folio-org/acq-models/pull/88, make location repeatable:
https://issues.folio.org/browse/MODGOBI-48
- Create a list of locations and add individual location to that list
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

MODGOBI-48 location repeatable

---

src/main/java/org/folio/gobi/GobiPurchaseOrderParser.java

Fix one more sonar cloud security issue:
https://issues.folio.org/browse/MODGOBI-49
- Disable DTD and external DTD feature to protect against XML entity attacks
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

Missing sonar cloud XXE vulnerability fix

---

src/main/java/org/folio/gobi/GobiPurchaseOrderParser.java
src/test/java/org/folio/gobi/HelperUtilsTest.java

Sonar shows a vulnerability on https://sonarcloud.io/project/issues?id=org.folio%3Amod-gobi&issues=AWkM5Pd6V9myJaMxKwVi&open=AWkM5Pd6V9myJaMxKwVi
However, after adding a dummy space on that line fixes it. Assumption is that sonar was unable to read that line

SONAR Issues

---

NEWS.md
pom.xml

[MODGOBI-50](https://issues.folio.org/browse/MODGOBI-50) Create release v1.2.1 following [Release procedure](https://dev.folio.org/guidelines/release-procedures/#maven-based-modules) guide.
* The required mod-gobi interface version dependencies are updated
* Update NEWS.md - scrap v1.2.0 as unreleased and release v1.2.1
Ideally all of the PRs involved in …

Release 1.2.1

---

pom.xml

[MODINVOSTO-2](https://issues.folio.org/browse/MODINVOSTO-2)  update module due to path changes in [folio-org/acq-models#99](https://github.com/folio-org/acq-models/pull/99)
- updated acq-modules
- updated sourceDirectory for jsonschema2pojo-maven-plugin in pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to …

Modinvosto 2 acq-models schema path change

---

src/main/resources/ListedElectronicSerial.json
src/main/resources/ListedPrintSerial.json
src/main/resources/UnlistedPrintSerial.json
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json

https://issues.folio.org/browse/MODGOBI-60
https://issues.folio.org/browse/MODGOBI-60 - Add default currency USD
- Added default currency USD to orders that do not send any Cost information
- Removed redundant code
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

MODGOBI-60- Add default Currency

---

src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/GOBIIntegrationServiceResourceImpl/vendor.json
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json

https://issues.folio.org/browse/MODGOBI-63 - Add single material type to physical and eresource separately
- Removed the conversion of material type to array
- Added material type mapping to physical and eresource and removed it from details
- Refactored the code to map the composite PO line fields to a separate method, to make it easier to map fields based on orderFormat
- Do PRs exist …

MODGOBI-63 - specify material type for physical and eresource

---

src/main/resources/UnlistedPrintMonograph.json

https://issues.folio.org/browse/MODGOBI-69: acq schemas have few fields that are made required.
Making the corresponding changes to mod-gobi
Added the missing field orderType for one order
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

MODGOBI-69- adding missing order type

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODGOBI-66 - 1.4.0 Release
Increased the dependency version for Order …

MODGOBI-66 - Release 1.4.0

---

src/main/java/org/folio/gobi/Mapper.java

https://issues.folio.org/browse/MODGOBI-71
Move owner to PO level …

MODGOBI-71-Mapping owner at PO level

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/ListedElectronicMonograph.json
src/main/resources/ListedElectronicSerial.json
src/main/resources/ListedPrintMonograph.json
src/main/resources/ListedPrintSerial.json
src/main/resources/UnlistedPrintMonograph.json
src/main/resources/UnlistedPrintSerial.json
src/main/resources/mapping.json
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json

https://issues.folio.org/browse/MODGOBI-74
* acq-model updates needed to implement mapping for fundDistribution
* Updated mapping for fundDistribution.  …
* Constants naming fixed for the `GOBIIntegrationServiceResourceImplTest` .
* Added module permissions.
* Added `pom.xml` property to force aspects compilation.
* Unit tests updated.
Ideally all of the …

MODGOBI-74 acq-model updates

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MockData/compositePurchaseOrder.json
src/test/resources/MockData/purchaseOrders.json

https://issues.folio.org/browse/MODGOBI-72 - Prevent duplicate Orders
1) Check for existing Order, and return PO Line Number if its existing
2) Retry to Open Order if its Pending
3) Create Order if any of the above steps fail, or order doesn't exist
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODGOBI-72- Check for existing order before creating

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/ListedElectronicMonograph.json
src/main/resources/ListedPrintMonograph.json
src/main/resources/mapping.json
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

https://issues.folio.org/browse/MODGOBI-73
Change Product type Id to UUID, to  handle multiple types in inventory while creating an instance
1. Add a lookup method to identifier-types
2. Set the UUID while creating the ORDER
3. Use default type ISBN to fetch UUID, and fall back to first one if not present(which is highly unlikely)
4. added test cases to exercise the scenario
- Do PRs …

MODGOBI-73- Product Type ID to UUID

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODGOBI-75
https://issues.folio.org/browse/MODGOBI-75
- Updating News.md
- Upgrading dependent version modules with latest release versions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODGOBI-75- Release 1.5.0

---

src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json

https://issues.folio.org/browse/MODGOBI-74?focusedCommentId=53446&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-53446
* fixed by proposed solution
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODGOBI-74 endless loop bug

---

src/test/resources/MockData/GOBI_organization.json

[MODORGS-32](https://issues.folio.org/browse/MODORGS-32) Include metadata property in JSON schemas …

MODORGS-32 Include metadata property in JSON schemas

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODGOBI-80
Release mod-gobi 1.6.0
Update dependent interface versions
update NEWS

MODGOBI-80- Release 1.6.0

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODORDERS-290 - Story adds new permission "orders.item.approve" to require approval before opening orders. 
- As orders from GOBI are implicitly approved, add the permission "orders.item.approve" to module permission
- Pointing to the latest acq-models
Ideally all of the PRs involved in breaking changes would be merged in …

MODORDERS-290- adding approve permission

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODGOBI-84
* Updated interface versions
* Updated release notes …

MODGOBI-84 Release 1.7.0

---

pom.xml

https://issues.folio.org/browse/MODGOBI-96
- change pom.xml
No other changes necessary
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …

MODGOBI-96: Increment RMB to 29.0.1

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Major changes in this release related to updating RMB fixing the memory leak and security issues, updating fund distribution schema.

MODGOBI-94 prepared release 1.8.0

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java

https://issues.folio.org/browse/MODGOBI-81
* mod-finance is called instead of mod-finance-storage 
* interface dependencies are updated
* module permissions are updated.
* Point acq-model to master
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

MODGOBI-81: use finance business logic module

---

descriptors/ModuleDescriptor-template.json

Organizations interface version updating. …

FOLIO-2436 - folio-testing build failure w/interface mismatch (organiztions-storage/orders)

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODGOBI-98] Create MODGOBI release

---

pom.xml

[MODGOBI-102](https://issues.folio.org/browse/MODGOBI-102) - Update to RMB v30.0.1
Update to RMB v30.0.1
RMB updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODGOBI-102 - Update to RMB v30.0.1

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[MODGOBI-101](https://issues.folio.org/browse/MODGOBI-101)
- Update news
- update acq-model
- update required interfaces orders:10.4, organizations-storage.organizations:3.1, finance.funds:1.1
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

Tmp release 1.10.0

---

Dockerfile
Jenkinsfile
pom.xml
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

https://issues.folio.org/browse/MODGOBI-107
* updated rmb to v31.1.1 …

MODGOBI-107 RMB 31.1.1

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

https://issues.folio.org/browse/MODGOBI-106
* release notes updated
* updated interface versions …

MODGOBI-106 release 1.11.0

---

pom.xml

Increase gobi version

---

src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/rest/impl/InitConfigService.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/mapping.json

https://issues.folio.org/browse/MODGOBI-109
* fixed futures pipeline for fundDistribution properties …

MODGOBI-109 fixed futures pipeline

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODGOBI-112
* updated release notes …

MODGOBI-112 release 1.11.1

---

NEWS.md

MODGOBI-112 release 1.11.1 news.md -> master branch

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/resources/MockData/compositePurchaseOrder.json

[MODGOBI-100](https://issues.folio.org/browse/MODGOBI-100) …

MODGOBI-100 Update the logic of checking the availability of orders and acq-module

---

pom.xml
src/main/java/org/folio/gobi/Mapper.java
src/main/resources/ListedElectronicMonograph.json
src/main/resources/ListedElectronicSerial.json
src/main/resources/ListedPrintMonograph.json
src/main/resources/ListedPrintSerial.json
src/main/resources/UnlistedPrintMonograph.json
src/main/resources/UnlistedPrintSerial.json
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

* Add POL tags from incoming GOBI data
* added tags mapping …

MODGOBI-110 Add POL tags from incoming GOBI data

---

pom.xml
src/main/java/org/folio/gobi/GobiPurchaseOrderParser.java
src/main/java/org/folio/gobi/GobiResponseWriter.java
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/gobi/OrderMappingCache.java
src/main/java/org/folio/gobi/exceptions/HttpException.java
src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java
src/main/java/org/folio/rest/impl/InitConfigService.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/log4j2.properties
src/test/java/org/folio/gobi/MappingHelperTest.java
src/test/java/org/folio/gobi/MappingTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/java/org/folio/rest/impl/PostGobiOrdersHelperTest.java
src/test/resources/log4j2.properties

https://issues.folio.org/browse/MODGOBI-117
* rmb updated
* project dependencies updated
* code refactoring …

MODGOBI-117 RMB 32.1.0

---

PERSONAL_DATA_DISCLOSURE.md
PERSONAL_DATA_DISCLOSURE.md.txt

[MODGOBI-118] - Add personal data disclosure form

---

NEWS.md
pom.xml

MODGOBI (mod-gobi) release > https://issues.folio.org/browse/MODGOBI-116
While it's …

MODGOBI (mod-gobi) release

---

pom.xml

[MODGOBI-0] Update the artifact version due to remove annessesary tag

---

pom.xml
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

https://issues.folio.org/browse/MODGOBI-122
* update rmb v33.0.0 …

MODGOBI-122 update rmb v33.0.0

---

src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java

https://issues.folio.org/browse/MODGOBI-122
* fixed query format …

MODGOBI-122 fixed query format

---

NEWS.md
pom.xml

* https://issues.folio.org/browse/MODGOBI-122
* updated release notes …

MODGOBI-121 release 2.1.0

---

src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/java/org/folio/rest/impl/PostGobiOrdersHelperTest.java
src/test/resources/GOBIIntegrationServiceResourceImpl/po_listed_print_serial.xml
src/test/resources/PostGobiOrdersHelper/empty_funds.json
src/test/resources/PostGobiOrdersHelper/valid_funds.json

https://issues.folio.org/browse/MODGOBI-123
Check whether FundCode contains separator ":". It should only be the case when expense class is sent together with fund code.
If separator is present, extract expense class from FundCode and add it to fundDistribution.
If not, everything works as before (e.g. sending expense class through LocalData4 is still possible).
- Do PRs exist for these …

MODGOBI-123-3

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODFISTO-244
* bump up finance.expense-classes interface version  …

MODFISTO-244 bump up finance.expense-classes interface version

---

descriptors/ModuleDescriptor-template.json

[MODORDSTOR-261] - Gobi : Update API version

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/mapping.json
src/test/java/org/folio/gobi/MappingHelperTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MockData/compositePurchaseOrder.json
src/test/resources/PostGobiOrdersHelper/empty_acquisition_methods.json
src/test/resources/PostGobiOrdersHelper/valid_acquisition_methods.json

Support Acquisition method as UUID reference
Lookup method was implemented to search acquisition method by name …

[MODGOBI-139] - Implement lookup for Acquisition Methods

---

pom.xml

https://issues.folio.org/browse/MODGOBI-140 …

MODGOBI-140. Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODGOBI-143 …

MODGOBI-143. Kiwi Hotfix 2.2.1

---

pom.xml

https://issues.folio.org/browse/MODGOBI-141 …

MODGOBI-141. Juniper R2 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODGOBI-142 …

MODGOBI-142. Juniper R2 2021 HF #5 module release

---

src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java

* https://issues.folio.org/browse/MODGOBI-144
* throw exception and stop the flow when organization not found …

MODGOBI-144 throw exception when organization not found

---

pom.xml
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/test/resources/GOBIIntegrationServiceResourceImpl/po_listed_print_monograph.xml

https://issues.folio.org/browse/MODGOBI-137
Set product id type to "Invalid ISBN" if ISBN is invalid. This way mod-orders will not try to validate ISBN if order from GOBI has invalid ISBN, and therefore order creation won't be aborted.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

MODGOBI-137

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODGOBI-147
* updated release notes …

MODGOBI-147 Lotus 2022 R1 module release 2.3.0

---

src/test/java/org/folio/gobi/MappingHelperTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

Reverts folio-org/mod-gobi#158

Revert "[MODGOBI-150]- Added Thread.sleep() to get complete response for asyn…"

---

src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/test/java/org/folio/gobi/MappingHelperTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MockData/GOBI_organization.json

[MODGOBI-132]-updated VendorDetails Mapping

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/main/resources/log4j2-json.properties
src/main/resources/mapping.json
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json
src/test/resources/MockData/GOBI_organization.json
src/test/resources/PostGobiOrdersHelper/acquisitions_units.json

* https://issues.folio.org/browse/MODGOBI-129
* https://issues.folio.org/browse/MODGOBI-129 …

MODGOBI-129 Add acquisition unit and internal note fields mappings

---

descriptors/ModuleDescriptor-template.json

[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking
- Updated schemas
- Updated affected API versions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

[MODFISTO-303] update for finance optimistic locking

---

src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/Mapper.java
src/test/java/org/folio/gobi/MappingHelperTest.java
src/test/resources/GOBIIntegrationServiceResourceImpl/po_listed_electronic_monograph.xml
src/test/resources/MockData/GOBI_organization.json

[MODGOBI-132]-modified mapvVendorAccount method.

---

src/main/java/org/folio/gobi/FieldMappingTranslatorResolver.java
src/main/resources/mapping.json

[MODGOBI-152] - Fix issue with lookup address

---

src/main/java/org/folio/gobi/Mapper.java

[MODGOBI-152] - Update logic to map receiving workflow

---

pom.xml
src/main/resources/mapping.json

Update mapping
While it's helpful for reviewers to help identify potential problems, …

[MODGOBI-160] - Updated mapping

---

src/main/java/org/folio/gobi/MappingDetailsService.java
src/main/java/org/folio/rest/impl/MappingApi.java
src/test/java/org/folio/gobi/MappingDetailsServiceTest.java

[MODGOBI-161] - Refactoring

---

src/main/java/org/folio/gobi/FieldMappingTranslatorResolver.java
src/main/java/org/folio/gobi/LookupService.java
src/main/java/org/folio/gobi/Mapper.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json

https://issues.folio.org/browse/MODGOBI-166
Move acq unit mapping logic in model to the translation object …

[MODGOBI-166]-added translater

---

src/main/java/org/folio/gobi/LookupService.java

[MODGOBI-166]-normalised GOBI accountNo.

---

descriptors/ModuleDescriptor-template.json

[MODGOBI-172]-added missing permissions

---

NEWS.md
descriptors/ModuleDescriptor-template.json

[MODGOBI-173] 2022 R2 Morning Glory v2.4.2 release

[MODGOBI-173] 2022 R2 Morning Glory v2.4.2 release

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODGOBI-172
* added missed permission …

MODGOBI-172 added missed permission

---

pom.xml

[MODGOBI-175]-upgraded raml

---

NEWS.md
pom.xml

[MODGOBI-177](https://issues.folio.org/browse/MODGOBI-177) …

[MODGOBI-177] - Release 2.5.0

---

NEWS.md
src/main/java/org/folio/completablefuture/FolioVertxCompletableFuture.java

[MODGOBI-179] - Module release Morning Glory R2 2022 Hot Fix #1

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/log4j2.properties
src/test/resources/log4j2.properties

https://issues.folio.org/browse/MODGOBI-178 …

[MODGOBI-178] Logging improvement - Configuration

---

src/main/java/org/folio/gobi/FieldMappingTranslatorResolver.java
src/main/java/org/folio/gobi/LookupService.java
src/test/java/org/folio/gobi/MappingTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java

[MODGOBI-186]-updated  mapping & pointed to latest schema

---

src/main/java/org/folio/gobi/LookupService.java
src/main/java/org/folio/gobi/Mapper.java

https://issues.folio.org/browse/MODGOBI-188
Added an additional  call to lookupOrganization() before mapping acqUnits.  
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

[MODGOBI-188]-updated mapping logic.

---

NEWS.md
pom.xml

[MODGOBI-189] - Release v2.6.0

---

ramls/gobi-custom-mappings.raml
src/main/java/org/folio/rest/impl/GobiOrdersCustomMappingsImpl.java

Resolves: [MODGOBI-187](https://issues.folio.org/browse/MODGOBI-187) Update dependent raml-util …

[MODGOBI-187] Update dependent raml-util

---

src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/MappingHelper.java
src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json

https://issues.folio.org/browse/MODGOBI-194
* fixed lookupAcquisitionUnitIdsByName mapping
* fixed logging …

MODGOBI-194 fixed lookupAcquisitionUnitIdsByName mapping

---

src/main/java/org/folio/rest/impl/GobiOrdersCustomMappingsImpl.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
src/test/java/org/folio/rest/impl/PostGobiOrdersHelperTest.java

* https://issues.folio.org/browse/MODGOBI-195
* added validation upon attempt of creating or updating custom mapping
* In order to avoid silent mapping using default mapping file, the logic changed to fail the whole process of order creation if custom mapping file is invalid
Ideally all of the PRs involved in breaking changes would be merged in the same …

MODGOBI-195 fixed custom mapping usage

---

ramls/gobi.raml
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/exceptions/ErrorCodes.java
src/main/java/org/folio/gobi/exceptions/GobiException.java
src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java

https://github.com/folio-org/mod-gobi/tree/MODGOBI-195
While it's helpful for reviewers …

[MODGOBI-195] - error handling improvement

---

NEWS.md
pom.xml

https://issues.folio.org/browse/MODGOBI-196 …

[MODGOBI-196] - Release v2.7.0

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Relese v2.7.1

---

pom.xml

https://issues.folio.org/browse/MODGOBI-197 …

[MODGOBI - 197] - Update RMB to 45.1.0 and vertx to the latest version

---

src/main/java/org/folio/rest/service/GobiCustomMappingsService.java

[MOGDOBI-206: Fix endpoint to load custom mappings](https://folio-org.atlassian.net/browse/MODGOBI-206)
* Fix endpoint behavior by including the fetched custom mappings in the response

[MODGOBI-206] Fix endpoint to load custom mappings

---

pom.xml

[https://folio-org.atlassian.net/browse/MODGOBI-205](https://folio-org.atlassian.net/browse/MODGOBI-205)
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146

[MODGOBI-205] mod-gobi: Upgrade RAML Module Builder

---

src/main/resources/ListedElectronicMonograph.json
src/main/resources/ListedElectronicSerial.json
src/main/resources/ListedPrintMonograph.json
src/main/resources/ListedPrintSerial.json
src/main/resources/UnlistedPrintMonograph.json
src/main/resources/UnlistedPrintSerial.json

See comments in https://folio-org.atlassian.net/browse/UIGS-22

MODGOBI-206. Change donor default mappings after feedback

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODFIN-358

MODFIN-358. Update finance.funds interface

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/gobi/DataSourceResolver.java
src/main/java/org/folio/gobi/HelperUtils.java
src/main/java/org/folio/gobi/LookupService.java
src/main/java/org/folio/gobi/Mapper.java
src/main/java/org/folio/gobi/domain/LocationTranslationResult.java
src/main/java/org/folio/rest/ResourcePaths.java
src/test/java/org/folio/gobi/MappingTest.java
src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
src/test/resources/Mapping/modgobi152_ListedPrintMonograph.json
src/test/resources/Mapping/modgobi152_po_listed_print_monograph.xml

https://folio-org.atlassian.net/browse/MODGOBI-209
Use different locations endpoint to obtain tenantId's as well. …

[MODGOBI-209] - Update location translation for central ordering

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODGOBI-213
consortium-search API update
While …

[MODGOBI-213] consortium-search API update

---

descriptors/ModuleDescriptor-template.json
pom.xml

https://folio-org.atlassian.net/browse/MODGOBI-212
- Added module descriptor validator dependency
- Fixed permissions

[MODGOBI-212] - fix Module Descriptor and add descriptor validator

---

pom.xml

[[MODGOBI-214] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODGOBI-214)
- Update versions
- Add module descriptor validator

[MODGOBI-214] Update libraries of dependant acq modules to the latest versions

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/FOLIO-4102
While it's helpful for reviewers to …

Release v2.9.0

---

src/main/java/org/folio/gobi/MappingDetailsService.java
src/test/java/org/folio/gobi/MappingDetailsServiceTest.java

https://folio-org.atlassian.net/browse/MODGOBI-211
While it's helpful for reviewers to …

[MODGOBI-211] - Hide specific mapping types

---

src/main/resources/UnlistedPrintMonograph.json

https://folio-org.atlassian.net/browse/MODGOBI-211?focusedCommentId=247224&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-247224
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

[MODGOBI-211] - Add selector to unlisted print monograph

---

Dockerfile
Jenkinsfile
pom.xml

[[FOLIO-4208] Update to mod-gobi Java 21](https://folio-org.atlassian.net/browse/FOLIO-4208)
Update java and dependency versions

[FOLIO-4208] Update to mod-gobi Java 21

---

NEWS.md
pom.xml

Release Sunflower R1 2025

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/gobi/Mapper.java

[MODORDSTOR-448](https://folio-org.atlassian.net/browse/MODORDSTOR-448) - Make user limit as string field & apply migration
- Updated models
- Changed cast to `String`
See [acq-models](https://github.com/folio-org/acq-models/pull/519) or [mod-orders-storage](https://github.com/folio-org/mod-orders-storage/pull/476) PRs (there are lots).
Ideally all of …

[MODORDSTOR-448] Change type of eresource.userLimit to string

---

.github/dependabot.yml
CODEOWNERS
PULL_REQUEST_TEMPLATE.md

https://folio-org.atlassian.net/browse/MODGOBI-226
- Setup dependant bot
- Add codeowners
- Simplify PR_TEMPLATE

MODGOBI-226. Setup dependabot for your module
