folio-org/mod-gobi

src/main/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImpl.java, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
Fixed bug. It was looking for the wrong header item, pointed it to x-okapi-token instead.
=> Extract from x-okapi-token instead of x-okapi-tenant for user_id!!

descriptors/ModuleDescriptor-template.json
Updated mod-gobi to depend on "orders 1.0" and provide the permission required to post a purchase order to mod-orders.
=> Towards MODGOBI-7: Add mod-orders module permissions

src/main/java/org/folio/gobi/DataSource.java, src/main/java/org/folio/gobi/HelperUtils.java, src/main/java/org/folio/gobi/Mapper.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/test/java/org/folio/gobi/MappingTest.java, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java, src/test/resources/Mapping/testdata.xml
Several changes:
* Rename `Mapping` -> `DataSource`, and `Mapping.map()` to `DataSource.resolve()`
* [MODGOBI-23](https://issues.folio.org/browse/MODGOBI-23) Add an optional `Combinator` parameter.  This is a generalized way to combine multiple fields.
* The idea is to specify an xpath expression that returns multiple nodes, and a combinator that tells the mapper how to combine them.  
* e.g. Concatenate two or more strings, or multiply two or more numbers.
* The main impetus for this was the estimated_price mapping...  It should be set to the value of `NetPrice` if present, or to `ListPrice * Quantity` if it isn't.  There wasn't any way to do this until now.
* This also cleans up the most common code path (no combinator) by splitting the concatenation logic into a combinator that now …
=> MODGOBI-23 (Combinators)

descriptors/ModuleDescriptor-template.json
Add the following to POST /gobi/orders (Required for lookups)
- "inventory-storage.material-types.collection.get"
- "inventory-storage.locations.collection.get"
-  "vendor.collection.get"
=> add missing module permissions

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/mapping.json, ramls/mappings.json, src/main/java/org/folio/gobi/HelperUtils.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/test/java/org/folio/rest/impl/PostGobiOrdersHelperTest.java, src/test/resources/ConfigData/success.json
Added a helper method to call mod-configuration to get configured mappings from GOBI orders to FOLIO orders. Added demo schemas for the mappings as well as a helper method to build the map. These will need to be updated/rewritten when the schemas are finalized. Same with the simple unit test.
Note: this was not tested against a real mod-configuration, just mocks of the expected results... So, keep that in mind. :) I wanted to get this in here sooner rather than later so the schemas could be integrated.
Update: I have now tested this against mod-configuration and the unit test passed.
=> Updates towards MODGOBI-24

src/main/resources/data-mapping.json
I will get a US created for the fields I could not map. 
There are few other fields on which a decision is pending on the details of what the default values must be ex: renewal_interval , renewal_cycle etc..
=> Adding Mappings for serial Orders

NEWS.md, descriptors/ModuleDescriptor-template.json
Enabling Mod-inventory-storage for a tenant is causing an error due to the locations interface upgrade
`Incompatible version for module mod-gobi-1.0.1-SNAPSHOT.64 interface locations. Need 2.1. Have 3.0`
=> Update locations interface version to add 3.0

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java
https://issues.folio.org/browse/MODGOBI-47
vendors Interfaces were renamed to suffix with storage. Corresponding changes need to be made to gobi.
Changing Vendors permissions to reflect rename of vendors to "vendors-storage"
Changing the vendor's endpoint for GET
=> Pointing to latest Vendors Interface

PULL_REQUEST_TEMPLATE.md
In order to reduce the chance of breaking the nightly folio-testing build by merging breaking changes to master, we need to be more careful and consider the wider impact of the merge.
Add a pre-merge checklist to the PR template.  Ideally the assignee of the PR will quickly go through the checklist before merging.
=> Add pre-merge checklist to PR template

src/main/java/org/folio/gobi/Mapper.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
https://issues.folio.org/browse/MODGOBI-46
- Change all occurrences of `po_line` to `compositePoLines`
- Update tests to handle the change
For testing purpose, I made changes to `acq-models/composite_purchase_order.json` and `acq-models/examples/composite_purchase_order.sample` locally and build is a success locally. This branch will fail in Jenkins until https://github.com/folio-org/acq-models/pull/48 is merged.
=> MODGOBI-46 : po_lines property is renamed to compositePoLines

src/main/java/org/folio/gobi/Mapper.java, src/main/java/org/folio/gobi/MappingHelper.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/main/resources/ListedElectronicMonograph.json, src/main/resources/ListedElectronicSerial.json, src/main/resources/ListedPrintSerial.json, src/main/resources/UnlistedPrintSerial.json, src/main/resources/mapping.json
https://issues.folio.org/browse/MODGOBI-52
https://issues.folio.org/browse/MODGOBI-54
Default Location must be fetched only if it not provided. Also the workflow status of an order must be OPEN irrespective of the order type.
1. Created a new method to handle pulling the first location from the locations endpoint and also added this as a fall back method if the look up for the provided location fails
2. To prevent sending a null entry for product t id, adding a new product id entry in the list if the product id and type both are present.
The API tests will still fail after this change as the material type is a required field for interaction with inventory. This will be fixed as part of another story
https://issues.folio.org/browse/MODGOBI-57
Before merging this PR, please go through the …
=> MODGOBI-52, MODGOBI-54: Use default location only if not specified 

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/gobi/HelperUtils.java, src/main/java/org/folio/gobi/Mapper.java, src/main/java/org/folio/gobi/MappingHelper.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/main/resources/ListedElectronicMonograph.json, src/main/resources/ListedPrintMonograph.json, src/main/resources/UnlistedPrintMonograph.json, src/main/resources/mapping.json, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java, src/test/resources/MappingHelper/Custom_ListedElectronicSerial.json, src/test/resources/MockData/compositePurchaseOrder.json
[MODGOBI-77](https://issues.folio.org/browse/MODGOBI-77) Contributor-name-type is required for contributor added to POL
In case the contributor is resolved, the logic searches for contributor name type id in the inventory by `Personal name` name or any if there is no such. If no any contributor name type found, the logic logs an error and ignores contributor (contributor name type is required field and without it validation will reject entire order)
=> MODGOBI-77 Contributor-name-type is required for contributor added to POL

pom.xml, src/main/resources/log4j.properties, src/main/resources/log4j2.properties
While troubleshooting an unrelated issue it was discovered that the default log level is ERROR.  Upon investigation it appears this is due to multiple log configuration files being pulled into the fat jar.  In order to avoid this we should exclude log configuration files from RMB and use our own.
* remove log4j.properties
* add a log4j2.properties (with level = info) in src/main/resources this will be pulled into the fat jar
* log4j2.properties (with level = debug) already lives in src/test/resources and is used during unit tests
Add exclude filters to the shade plugin:
* log4j2.properties from RMB
* log4j.properties from anywhere
Also, see https://issues.folio.org/browse/RMB-447
- Does this PR meet …
=> exclude log properties from RMB

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
=> MODGOBI-95 FOLIO-2358 manage container memory

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/gobi/Mapper.java, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java, src/test/resources/MockData/compositePurchaseOrder.json
Handle breaking changes in [MODORDERS-349](https://issues.folio.org/browse/MODORDERS-349)
- updating acq-models
- updating interface dependency version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> MODORDERS-349 Make title schema changes to all APIs

src/main/resources/ListedElectronicMonograph.json, src/main/resources/ListedElectronicSerial.json, src/main/resources/ListedPrintMonograph.json, src/main/resources/ListedPrintSerial.json, src/main/resources/UnlistedPrintMonograph.json, src/main/resources/UnlistedPrintSerial.json, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
https://issues.folio.org/browse/MODGOBI-109
Previously we were not able to edit a fund on open orders , but now that has changed and having a random fundId be assigned if a fund Id is not found with a given fundcode is confusing, so changing the logic to not send a fundId if one is not found
- Remove the default translation, and do not send any fund Id if fund Id sent in GOBI order is not found
- Are the JIRAs under active …
=> MODGOBI-109: Avoid using default FundId if fundId not found

src/main/java/org/folio/gobi/Mapper.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java
https://issues.folio.org/browse/MODGOBI-109
The FundDistribution schema has a default value of DistributionType, hence it was still setting the funDistribution Object without a code which is a mandatory field in Orders schema
- Remove the DistributionType if the fundId is not valid
- Do not set the fundDistribution object when there are no values
- Also fixed a minor equals comparison with a Boolean(It could throw a potential NPE ) 
- Do JIRAs exist to update the impacted …
=> MODGOBI-109: Removing default DistributionType if there is no FundId

pom.xml
There is a lot of failures in karate tests today,
In logs in karate report I see 10 occurences of this error:
status code was: 500, expected: 201, response time in milliseconds: 282, url: https://folio-testing-karate-okapi.ci.folio.org/orders/order-lines, response: { "errors" : [ { "message" : "Generic error", "code" : "genericError", "parameters" : [ ], "cause" : "Unrecognized field \"recordsSource\" (class org.folio.rest.jaxrs.model.Config), not marked as ignorable (10 known properties: \"default\", \"userId\", \"id\", \"module\", \"configName\", \"metadata\", \"enabled\", \"code\", \"description\", \"value\"])\n at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.folio.rest.jaxrs.model.Configs[\"configs\"]->java.util.ArrayList[0]->org.folio.rest.jaxrs.model.Config[ …
=> Increase version of mod-configuration client in order to fix karate tests

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/gobi.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODGOBI-191 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/java/org/folio/gobi/LookupService.java
https://folio-org.atlassian.net/browse/MODGOBI-209
UnlistedPrintSerial https://github.com/folio-org/mod-gobi/blob/fc61a539798f4be58d78cc6997cd7d1b013837f1/ramls/schemas/GobiPurchaseOrder.xsd#L418 don't have location in mapping but it needs in poLine. based on previous implementation there is not support DEFAULT_LOOKUP_CODE in location search 
- Supported default lookup code for location search for UnlistedPrintSerial mapping
=> [MODGOBI-209] - Supported default lookup code for location search

src/main/java/org/folio/gobi/Mapper.java, src/main/java/org/folio/rest/impl/PostGobiOrdersHelper.java, src/test/java/org/folio/gobi/MappingTest.java, src/test/java/org/folio/rest/impl/GOBIIntegrationServiceResourceImplTest.java, src/test/resources/MockData/compositePurchaseOrder.json, src/test/resources/PostGobiOrdersHelper/valid_po_line_collection.json
[MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269) - Remove alerts and reporting codes from order lines, use a single order line schema
- Use a single po line schema, no more "composite po line"
- See [mod-orders-storage](https://github.com/folio-org/mod-orders-storage/pull/477)
- Required for compilation: [acq-models](https://github.com/folio-org/acq-models/pull/520)
- Are the JIRAs under active development? …
=> [MODORDERS-1269] Single po line schema, no sub-object

src/main/java/org/folio/gobi/Mapper.java
[MODGOBI-208] Adjust receiving workflow based on receipt status
Override POL's checkinItems flag when receipt status is "Receipt Not Required"
=> [MODGOBI-208] Adjust receiving workflow based on receipt status

ramls/schemas/GobiPurchaseOrder.xsd
- <https://folio-org.atlassian.net/browse/MODGOBI-193>
- Update GobiPurchaseOrder.xsd with new top-level SuppressInstanceFromDiscovery field
- This will help to resolve a problem found during the design of Karate tests:
=> [MODGOBI-193]. Update GobiPurchaseOrder.xsd
